language: c

dist: trusty
sudo: false

addons:
 apt:
  sources:
   - sourceline: 'deb https://dl.bintray.com/libgit2/ci-dependencies trusty libgit2deps'
     key_url: 'https://bintray.com/user/downloadSubjectPublicKey?username=bintray'
  packages:
   curl
   libssl-dev
   libmbedtls

matrix:
 fast_finish: true
 include:
   - os: linux
     compiler: clang
     env:
       - OPTIONS="-DCRYPT=openssl"
   - os: linux
     compiler: gcc
     env:
       - OPTIONS="-DCRYPT=openssl"
   - os: linux
     compiler: clang
     env:
       - OPTIONS="-DCRYPT=mbedtls"
   - os: linux
     compiler: gcc
     env:
       - OPTIONS="-DCRYPT=mbedtls"
   - os: osx
     compiler: clang

   - os: linux
     compiler: gcc
     env:
       - COVERITY=1
         OPTIONS="-DCRYPT=openssl"

script:
 - scripts/cibuild.sh

branches:
 only:
   - master
   - /^maint.*/
