language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

dist: trusty
sudo: false

addons:
 apt:
  packages:
   libssl-dev

matrix:
 fast_finish: true
 exclude:
   - os: osx
     compiler: gcc

script:
 - scripts/cibuild.sh

branches:
 only:
   - master
   - /^maint.*/
